---
- name: Get ARA json data
  shell: |  # noqa 305
    {{ local_working_dir }}/bin/ara result list --all -f json
  register: ara_data
  changed_when: false

- name: Send to graphite
  ara_graphite:
    graphite_host: "{{ ara_graphite_server }}"
    ara_mapping: "{{ ara_tasks_map }}"
    ara_data: "{{ ara_data.stdout|to_json }}"
    graphite_prefix: "{{ ara_graphite_prefix }}"
    only_successful_tasks: "{{ ara_only_successful_tasks }}"
