---
- name: Load sova patterns from URL
  uri:
    url: https://opendev.org/openstack/tripleo-ci-health-queries/raw/branch/master/output/sova-patterns.json
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  retries: 3  # to avoid accidental failures due to networking or rate limiting
  delay: 60
  register: pattern_config

- name: Run sova task
  sova:
    config: "{{ pattern_config.json }}"
    files:
      console: "{{ ansible_user_dir }}/workspace/logs/quickstart_install.log"
      errors: "/var/log/errors.txt"
      "ironic-conductor": "/var/log/containers/ironic/ironic-conductor.log"
      syslog: "/var/log/journal.txt"
      logstash: "/var/log/extra/logstash.txt"
      registry_log: "/var/log/extra/podman/containers/docker_registry/stdout.log"
    result: "{{ ansible_user_dir }}/workspace/logs/failures_file"
    result_file_dir: "{{ ansible_user_dir }}/workspace/logs"

- name: Run sova task (denials)
  sova:
    config: "{{ pattern_config.json }}"
    files:
      selinux: "/var/log/extra/denials.txt"
    result: "{{ ansible_user_dir }}/workspace/logs/selinux_denials.log"
